---
title: "Genome-quebec_Mapping"
author: "Claudia"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Package
```{r} 
library(leaflet)
library(leafem) #package de widgets dont "addMouseCoordinates"
library(leaflet.extras)
library(dplyr)

```


#Carte des espèces de poissons
```{r}

# Eliminer les valeurs manquantes 
fishData1<-gsheet2tbl("https://docs.google.com/spreadsheets/d/1xRhjszPQpBNGDPy_O8rTBwMlMt8tBXHgsoCMpl_bFJQ/edit#gid=1480193508")
fishData1
fishData1 <- na.omit(fishData1)

# carte fish
fishMap<-leaflet() %>% 
setView(lng = -73.70813912039158, lat = 45.60938582346861, zoom = 18) %>% 
  addTiles(group = "Carte des poissons") %>%
#Ajouter des marqueurs avec les noms des sites
  addMarkers(data=fishData1,lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces de poissons") %>%
   addScaleBar(       #ajout de l'échelle
    position = "bottomleft" #positionnement de l'échelle en bas à gauche
  ) %>%
#Ajouter une mini carte en bas dans le coin droit de la carte 
  addMiniMap(
       toggleDisplay = FALSE)%>% 
  addMouseCoordinates()%>%  # Ajout des coordonnées GPS du pointeur de la souris
  addResetMapButton()%>%  # ajout du bouton "reset" pour recentrage carte   
  addFullscreenControl()%>% #ajout du basculement en mode plein écran
  addSearchOSM()%>% #ajout de la barre de recherche Openstreetmap
  addCircleMarkers(data = fishData1,
                   lng = ~fishData1$`Longitude(X)`,
                   lat = ~fishData1$`Latitude(Y)`,
#FillColor - specifies that if the column has the number 3 then the markers will be green
                   fillColor = ~ifelse(fishData1$Color_fish_invert == 3, "#32CD32"),
                   fillOpacity = 2)%>%

# Position de la légende sur la carte,  # Couleurs uniques de la légende, # Libellés correspondant aux couleurs, # Titre de la légende
  addLegend(position = "bottomright",  
            colors = unique(fishData1$TypeEchantillon), 
            labels = unique(fishData1$TypeEchantillon),  
            title = "Légende du type d'échantillon"
  )

 ## Ajouter Type d'échantillon

fishMap<-fishMap %>%
  addMarkers(data=fishData1, lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon poissons") %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces de poissons","Type d'échantillon poissons"),
    options = layersControlOptions(collapsed = TRUE)
  )
fishMap
```

#Carte des espèces de invertébré
```{r}
# eleminer les valeur manquante 
invertebratesData<-gsheet2tbl("https://docs.google.com/spreadsheets/d/1guPot-d5chEHyjYUn_Ufx51YMRfCkJGOOFLAnS1luhE/edit#gid=0")
invertebratesData

invertebratesData <- na.omit(invertebratesData)

# carte inverterbrates
invertMap<-leaflet() %>% 
setView(lng = -73.28332496, lat = 45.44691702, zoom = 11) %>% 
  addTiles(group = "Carte des invertébrés") %>%
#Ajouter des marqueurs avec les noms des sites d'échantillonnage des invertébrés
  addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$SiteEchantillonnage, 
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces d'invertébrés") %>%
#Ajouter une barre d'échelle
 addScaleBar(       #ajout de l'échelle
    position = "bottomleft" #positionnement de l'échelle en bas à gauche
  ) %>%
#Ajouter une mini carte en bas dans le coin droit de la carte 
  addMiniMap(
       toggleDisplay = FALSE)%>% 
  addMouseCoordinates()%>%  # Ajout des coordonnées GPS du pointeur de la souris
  addResetMapButton()%>%  # ajout du bouton "reset" pour recentrage carte   
  addFullscreenControl()%>% #ajout du basculement en mode plein écran
  addSearchOSM()%>% #ajout de la barre de recherche Openstreetmap

  addCircleMarkers(data = invertebratesData,
                   lng = ~invertebratesData$`Longitude(X)`,
                   lat = ~invertebratesData$`Latitude(Y)`,
#FillColor - specifies that if the column has the number 3 then the markers will be red
                   fillColor = ~ifelse(invertebratesData$Color_fish_invert == 4, "#FF0000"),
                   fillOpacity = 2)%>%
  
 # Position de la légende sur la carte,  # Couleurs uniques de la légende, # Libellés correspondant aux couleurs, # Titre de la légende
  addLegend(position = "bottomright",  
            colors = unique(invertebratesData$TypeEchantillon), 
            labels = unique(invertebratesData$TypeEchantillon),  
            title = "Légende du type d'échantillon" 
  )

 ## Ajouter Type d'échantillon
invertMap<-invertMap %>%
  addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon d'invertébrés") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces d'invertébrés","Type d'échantillon d'invertébrés"),
    options = layersControlOptions(collapsed = TRUE)
  )

invertMap


```

#Carte des espèces de Poisson et invertébré (Carte basique invertMap)
```{r}
# carte fish + invertabrate
FishInvertMap <- invertMap%>%
#Ajouter des marqueurs : label en passant la souris et popup lorsqu'on clique sur le marqueur
  addMarkers(data=fishData1,lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, label=fishData1$TypeEchantillon, popup=fishData1$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces de poissons") %>%
  addMarkers(data=fishData1, lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, label=fishData1$SiteEchantillonnage, popup=fishData1$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon poissons") %>%
  addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, label=invertebratesData$TypeEchantillon, popup=invertebratesData$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces d'invertébrés") %>%
  addMarkers(data=invertebratesData, lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, label=invertebratesData$SiteEchantillonnage, popup=invertebratesData$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon d'invertébrés") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces de poissons","Type d'échantillon poissons","Site d'échantillonnage des espèces d'invertébrés","Type d'échantillon d'invertébrés"),
    options = layersControlOptions(collapsed = TRUE)
  ) 

FishInvertMap
```

#Carte des espèces de Poisson et invertébré (Carte basique fishMap)
```{r}
# carte fish + invertabrate
FishInvertMap1 <- fishMap%>%
#Ajouter des marqueurs : label en passant la souris et popup lorsqu'on clique sur le marqueur
  addMarkers(data=fishData1,lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, label=fishData1$TypeEchantillon, popup=fishData1$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces de poissons") %>%
  addMarkers(data=fishData1, lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, label=fishData1$SiteEchantillonnage, popup=fishData1$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon poissons") %>%
  addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, label=invertebratesData$TypeEchantillon, popup=invertebratesData$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces d'invertébrés") %>%
  addMarkers(data=invertebratesData, lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, label=invertebratesData$SiteEchantillonnage, popup=invertebratesData$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon d'invertébrés") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces de poissons","Type d'échantillon poissons","Site d'échantillonnage des espèces d'invertébrés","Type d'échantillon d'invertébrés"),
    options = layersControlOptions(collapsed = TRUE)
  ) 

FishInvertMap1
```

#Superposition carte
```{r}
FishInvertMap <- invertMap%>%

  addMarkers(data=fishData1,lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces de poissons") %>%
  addMarkers(data=fishData1, lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon poissons") %>%addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces d'invertébrés") %>%
  addMarkers(data=invertebratesData, lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon d'invertébrés") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces de poissons","Type d'échantillon poissons","Site d'échantillonnage des espèces d'invertébrés","Type d'échantillon d'invertébrés"),
    options = layersControlOptions(collapsed = TRUE)
  ) 

FishInvertMap

# carte fish + invertabrate
FishInvertMap1 <- fishMap%>%

  addMarkers(data=fishData1,lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces de poissons") %>%
  addMarkers(data=fishData1, lng= ~fishData1$`Longitude(X)`, lat= ~fishData1$`Latitude(Y)`, popup=fishData1$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon poissons") %>%addMarkers(data=invertebratesData,lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$SiteEchantillonnage,
             clusterOptions = markerClusterOptions, group = "Site d'échantillonnage des espèces d'invertébrés") %>%
  addMarkers(data=invertebratesData, lng= ~invertebratesData$`Longitude(X)`, lat= ~invertebratesData$`Latitude(Y)`, popup=invertebratesData$TypeEchantillon,
             clusterOptions = markerClusterOptions, group = "Type d'échantillon d'invertébrés") %>%
  addLayersControl(
    overlayGroups = c("Site d'échantillonnage des espèces de poissons","Type d'échantillon poissons","Site d'échantillonnage des espèces d'invertébrés","Type d'échantillon d'invertébrés"),
    options = layersControlOptions(collapsed = TRUE)
  ) 

FishInvertMap1


# Ajouter les deux cartes en tant que couches superposées
carteSuperposee <- carteSuperposee %>%
  addLayersControl(
    overlayGroups = c("FishInvertMap", "FishInvertMap1"),
  options = layersControlOptions(collapsed = TRUE)
  ) 

# Afficher la carte superposée
carteSuperposee
```